"""Return the tiny DeepSeek V4 preset used for tests and smoke runs."""
deepseek_v4_tiny() = DeepSeekV4Config(
    vocab_size=512,
    dim=64,
    n_heads=4,
    max_seq_len=64,
    n_layers=4,
    csa_compression=4,
    hca_compression=8,
    attention_topk=2,
    attention_window=4,
    query_compression_dim=16,
    indexer_dim=8,
    indexer_heads=2,
    attention_groups=2,
    attention_group_dim=16,
    n_experts=4,
    n_shared_experts=1,
    n_experts_per_tok=2,
    expert_dim=16,
    hash_routed_layers=1,
    mtp_tokens=2,
    n_hyper_connections=2,
)

"""Return the larger Flash-style DeepSeek V4 preset."""
deepseek_v4_flash() = DeepSeekV4Config(
    vocab_size=102_400,
    dim=7_168,
    n_heads=56,
    max_seq_len=1_000_000,
    n_layers=61,
    rope_theta=1_000_000.0f0,
    csa_compression=64,
    hca_compression=256,
    attention_topk=8,
    attention_window=512,
    query_compression_dim=2_048,
    indexer_dim=128,
    indexer_heads=8,
    attention_groups=8,
    attention_group_dim=512,
    n_experts=128,
    n_shared_experts=1,
    n_experts_per_tok=6,
    expert_dim=1_408,
    hash_routed_layers=4,
    mtp_tokens=2,
    n_hyper_connections=4,
)

"""Return the larger Pro-style DeepSeek V4 preset."""
deepseek_v4_pro() = DeepSeekV4Config(
    vocab_size=102_400,
    dim=8_192,
    n_heads=64,
    max_seq_len=1_000_000,
    n_layers=80,
    rope_theta=1_000_000.0f0,
    csa_compression=64,
    hca_compression=256,
    attention_topk=8,
    attention_window=512,
    query_compression_dim=2_304,
    indexer_dim=128,
    indexer_heads=8,
    attention_groups=8,
    attention_group_dim=640,
    n_experts=256,
    n_shared_experts=1,
    n_experts_per_tok=8,
    expert_dim=1_536,
    hash_routed_layers=6,
    mtp_tokens=2,
    n_hyper_connections=4,
)
